### ISSUE TITLE
Error run tdlib after building 

### ISSUE THREAD

**Issue by Kruizi** [tdlib/td#1164]
Hello

I am building the project according to the instructions 
I am building to the instructions [build](https://tdlib.github.io/td/build.html?language=Go)
Ubuntu 16 and clang ++

`apt-get update && apt-get upgrade && apt-get install make git zlib1g-dev libssl-dev gperf php cmake clang libc++-dev nano wget golang && git clone https://github.com/tdlib/td.git && cd td && rm -rf build && mkdir build && cd build`

`export CXXFLAGS="-stdlib=libc++"`

`CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH=/usr/local ..`

`cmake --build . --target install`

After the build, I run [go-tdlib](https://github.com/Arman92/go-tdlib/blob/master/examples/authorization/basicAuthorization.go)
I get an error that contains a lot of lines message. I attach file with errors at the comment.

The script ran on Ubuntu 16.04 from under docker-compose

```
version: "3"
services:
   ubuntu:
     image: addle / ubuntu-16.04
     working_dir: / srv / golang
     volumes:
       -.: / srv / golang
```

What could be the problem ?

[error_logs.txt](https://github.com/tdlib/td/files/5046591/error_logs.txt)
